server:
  port: 7002
spring:
  application:
    name: auth-server
  profiles:
    active: mongo
eureka:
  instance:
    instance-id: auth-server
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://eureka-center-01:8761/eureka/
    fetch-registry: true
    register-with-eureka: true