server:
  port: 7001

spring:
  application:
    name: login-server
  profiles:
    active: mongo

eureka:
  instance:
    instance-id: login-server
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://eureka-center-01:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 5