server:
  port: 7003

spring:
  application:
    name: content-server
  profiles:
    active: mongo

eureka:
  instance:
    instance-id: content-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-center-01:8761/eureka/
    fetch-registry: true
    register-with-eureka: true