server:
  port: 8761

spring:
  application:
    name: eureka-center-01

eureka:
  instance:
    hostname: eureka-center-01
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false
