server:
  port: 8080

spring:
  application:
    name: eureka-consumer
  profiles:
    active: mongo

eureka:
  instance:
    instance-id: eureka-consumer
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://eureka-center-01:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5