server:
  port: 8080

spring:
  application:
    name: eureka-consumer
  profiles:
    active: mongo
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  auth:


eureka:
  instance:
    instance-id: eureka-consumer
  client:
    service-url:
      defaultZone: http://eureka-center-01:8761/eureka/
    fetch-registry: true
    register-with-eureka: true